POST {{baseUrl}}/certificate
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "AWS Certified Developer",
  "issuer": "Amazon Web Services",
  "issueDate": "2024-03-15",
  "url": "https://aws.amazon.com/certification"
}
