POST {{baseUrl}}/users/1/change-password
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword": "Trudne12@",
  "newPassword1": "NoweHaslo1!",
  "newPassword2": "NoweHaslo1!"
}
